stud_auth/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from .views import test


urlpatterns = patterns('',
                       url('^test-inner/(?P<arg>\w+)/$', test, name='test_inner'),
                      )

studentsdb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from registration.backends.default import views as registration_views
from django.contrib.auth import views as auth_views
# from django.core.urlresolvers import reverse

from .settings import MEDIA_ROOT, DEBUG

from students.views.students import StudentUpdateView, StudentDeleteView, StudentList
from students.views.students import students_ajax_next_page
from students.views.students import students_delete_bunch
from students.views.students_add import students_add
# from students.views.custom_contact_form import CustomContactFormView
from students.views.contact_admin import ContactAdminView
from students.views.groups import groups_list
from students.views.groups import GroupDeleteView
from students.views.groups import GroupUpdateView
from students.views.groups import GroupCreateView
from students.views.journal import JournalView
from students.views.action_journal import ActionListView
from stud_auth.views import UsersListView, UserDetailView, UserUpdateView
from stud_auth.forms import CustomLoginForm

# test
from stud_auth.views import test

# need for i18n pattern
js_info_dict = {
    'packages': ('students',),
    'domain': 'djangojs',
}

urlpatterns = patterns(
    '',
    # Students urls
    url(r'^$', 'students.views.students.students_list', name='home'),
    url(r'^students/add/$',
        permission_required('students.add_student')(students_add),
        name='students_add'),
    # url(r'^students/(?P<sid>\d+)/edit/$',
    #     'students.views.students.students_edit', name='students_edit'),
    # url(r'^students/(?P<pk>\d+)/delete/$',
    #     'students.views.students.students_delete', name='students_delete'),
    url(r'^students/(?P<pk>\d+)/edit/$',
        StudentUpdateView.as_view(), name='students_edit'),
    url(r'^students/(?P<pk>\d+)/delete/$',
        permission_required('students.delete_student')(StudentDeleteView.as_view()),
        name='students_delete'),
    url(r'^student_list/$', StudentList.as_view(), name='student_list'),

    # trying ajax
    url(r'students/next_page$',
        students_ajax_next_page, name='students_ajax_next_page'),

    # delete bunch of students
    url(r'^students/delete-bunch/$',
        permission_required('students.delete_student')(students_delete_bunch),
        name="students_delete_bunch"),


    # Groups urls
    url(r'^groups/$', groups_list, name='groups'),
    # url(r'^groups/add/$',
    #     'students.views.groups.groups_add', name='groups_add'),
    url(r'^groups/add/$', permission_required('students.add_group')(GroupCreateView.as_view()), name="groups_add"),
    # url(r'^groups/(?P<pk>\d+)/edit/$',
    #     'students.views.groups.groups_edit', name='groups_edit'),
    url(r'^groups/(?P<pk>\d+)/edit/$',
        permission_required('students.change_group')(GroupUpdateView.as_view()), name="group_edit"),
    url(r'^groups/(?P<pk>\d+)/delete/$',
        login_required(permission_required(
            'students.delete_group',
            raise_exception=True)(GroupDeleteView.as_view())),
        name='group_delete'),

    # Journal url
    # url(r'^journal/$', 'students.views.journal.journal_list', name='journal'),
    # url(r'^journal/$', JournalView.as_view(), name='journal'),
    url(r'^journal/(?P<pk>\d+)?/?$',
        login_required(JournalView.as_view()), name='journal'),

    # Admin page
    url(r'^admin-page/', include(admin.site.urls)),

    # favicon.ico
    # url(r'^/favicon\.ico/$',
    #     RedirectView.as_view(url='/static/img/favicon.ico')),


    # Contact Admin Form
    url(r'^contact-admin/$', login_required(ContactAdminView.as_view()),
        name='contact_admin'),
    # contact admin with application django-contact-form
    # url(r'^contact-form/$', include('contact_form.urls')),
    # url(r'^contact-form/$',
    #     CustomContactFormView.as_view(), name='contact_form'),

    # Action List
    url(r'^action-journal/$',
        login_required(ActionListView.as_view()), name='action_journal'),

    # i18n
    url(r'^jsi18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),
    # set_language view
    url('^set-language/$',
        'students.views.set_language.set_language', name='set_language'),

    # User related urls
    url(r'^users/profiles/$', login_required(UsersListView.as_view()), name='users_list'),
    url(r'^users/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name='profile'),
    # url(r'^users/profile/(?P<username>[a-zA-Z@+-_.0-9]+)/$',
    #     login_required(UserDetailView.as_view()), name='user_profile'),
    url(r'^users/profile/(?P<pk>\d+)/$',
        login_required(UserDetailView.as_view()), name='user_profile'),
    url(r'^users/profile/edit/$',
        login_required(UserUpdateView.as_view()), name='user_profile_edit'),
    url(r'^users/logout/$',
        auth_views.logout, kwargs={'next_page': 'home'}, name='auth_logout'),
    url(r'^users/register/complete/$', TemplateView.as_view(
        template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^users/activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'),
    url(r'^users/password_reset/$',
        auth_views.password_reset, name='auth_password_reset'),
    url(r'^users/register/$',
        registration_views.RegistrationView.as_view(),
        name='registration_register'),
    url(r'^users/activate/(?P<activation_key>\w+)/$',
        registration_views.ActivationView.as_view(),
        name='registration_activate'),
    url(r'^users/password_reset/done/$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^users/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^users/reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^users/password_change/$', auth_views.password_change,
        name='password_change'),
    url(r'^users/password_change/done/$',
        RedirectView.as_view(pattern_name='profile'),
        name='password_change_done'),
    url(r'^users/login/$',
        auth_views.login, {'template_name': 'registration/login.html',
                           'authentication_form': CustomLoginForm},
        name='users_login'),
    url(r'^users/',
        include('registration.backends.default.urls', namespace='users')),

    # Social Auth Related urls
    url(r'^social/',
        include('social.apps.django_app.urls', namespace='social')),

    # test
    url(r'^test/$', test, name='test'),
    url(r'^test/', include('stud_auth.urls', namespace='test_stud_auth')),
)

if DEBUG:
    # serve files from media folder
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve', {'document_root': MEDIA_ROOT})
    )

    # for debug_toolbar
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

students/models/action.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Action(models.Model):
    class Meta(object):
        verbose_name = _(u'action')
        verbose_name_plural = _(u'actions')

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
        verbose_name=_('action time'),
    )
    action_detail = models.CharField(
        verbose_name=_(u'action descriprion'),
        blank=False,
        max_length=256,
    )
    model_name = models.CharField(
        verbose_name=_(u'model name'),
        blank=False,
        max_length=256,
    )
    model_verbose_name = models.CharField(
        verbose_name=_(u'model verbose name'),
        blank=False,
        max_length=256,
    )

    def __unicode__(self):
        return u"%s (%s)" % (self.model_name, self.model_verbose_name)

students/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse

# Views for Students

def students_list(request):
    students = (
	{'id': 1,
	 'first_name': u'Віталій',
	 'last_name': u'Подоба',
	 'ticket': 235,
	 'image': 'img/1.jpg'},
	{'id': 2,
	 'first_name': u'Андрій',
	 'last_name': u'Корост',
	 'ticket': 2123,
	 'image': 'img/2.jpg'},
	{'id': 3,
	 'first_name': u'Антон',
	 'last_name': u'Разгільдяй',
	 'ticket': 512,
	 'image': 'img/3.gpj'}
    )
    return render(request, 'students/students_list.html', {'students':students})

def students_add(request):
    return HttpResponse('<h1>Student Add Form</h1>')

def students_edit(request, sid):
    return HttpResponse('<h1>Edit Student %s</h1>' % sid)

def students_delete(request, sid):
    return HttpResponse('<h1>Delete Student %s' % sid)

# Views for Groups

def groups_list(request):
    groups = (
        {'id':1,
	 'name': u'МтМ-21',
         'headman': u'Віталій Подоба'},
        {'id': 2,
	 'name': u'МтМ-22',
         'headman': u'Андрій Корост'},
        {'id': 3,
	 'name': u'МтМ-23',
         'headman': u'Антон Разгільдяй'}
    )
    return render(request, 'students/groups_list.html', {'groups':groups})


def groups_add(request):
    return HttpResponse('<h1>Group Add Form</h1>')

def groups_edit(request, gid):
    return HttpResponse('<h1>Edit Group %s' % gid)

def groups_delete(request, gid):
    return HttpResponse('<h1>Delete Group %s</h1>' % gid)

students/views/action_journal.py
#from time import sleep
from django.views.generic import ListView

from ..models.action import Action

# from ..util import paginate


class ActionListView(ListView):
    model = Action
    template_name = 'students/action_journal.html'
    queryset = Action.objects.all().order_by('timestamp').reverse()[:100]
    context_object_name = 'actions'
    #
    # def get_context_data(self, **kwargs):
    #     context = super(ActionListView, self).get_context_data(**kwargs)
    #     context = paginate(self.queryset, 10, self.request, context, var_name='actions')
    #     # sleep(1)
    #     return context

students/views/contact_admin.py
import logging

from django import forms
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.views.generic import FormView
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

from studentsdb.settings import ADMIN_EMAIL

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from ..signals import contact_admin_sent


class ContactAdminForm(forms.Form):
    def __init__(self, *args, **kwargs):
        # call original initialiazator
        super(ContactAdminForm, self).__init__(*args, **kwargs)

        # this helper object allows us to customize form
        self.helper = FormHelper()

        # form tag attributes
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        #self.helper.form_action = reverse('contact_admin')

        # twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10 form-field-width'

        # form buttons
        self.helper.add_input(Submit('send_button', _(u'Send')))

    from_email = forms.EmailField(
        label=_(u"Your email"))

    subject = forms.CharField(
        label=_(u"Message title"),
        max_length=128)

    message = forms.CharField(
        label=_(u"Message"),
        max_length=2500,
        widget=forms.Textarea)

    recipient_list = [ADMIN_EMAIL]

    def send_email(self):
        data = self.cleaned_data
        send_mail('[contact admin form] ' + data.get('subject'),
                  'From: ' + data.get('from_email') + '\n\n' + data.get('message'),
                  data.get('from_email'),
                  [ADMIN_EMAIL]
                 )



class ContactAdminView(FormView):
    form_class = ContactAdminForm
    template_name = 'contact_admin/form.html'

    # @method_decorator(permission_required('auth.add_user'))
    def dispatch(self, *args, **kwargs):
        return super(ContactAdminView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('contact_admin')

    def form_valid(self, form):
        try:
            form.send_email()
        except Exception:
            message = _(u"Some trouble happend. Message not sent. Please, try later.")
            messages.info(self.request, message)
            logger = logging.getLogger(__name__)
            logger.exception(message)
        else:
            messages.info(self.request, _(u"Message sent successfully"))
            # send a signal
            form_data = self.get_form_kwargs().get('data')
            message_subject = form_data.get('subject')
            message_sender = form_data.get('from_email')
            contact_admin_sent.send(sender=self.__class__,
                                    message_subject=message_subject,
                                    message_sender=message_sender
                                   )
        return super(ContactAdminView, self).form_valid(form)



'''
def contact_admin(request):
    # check if form was posted
    if request.method == 'POST':
        # create a form instance and populate it
        # with data from the request
        form = ContactAdminForm(request.POST)

        # check whether user data is valid:
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']
            try:
                send_mail(subject, from_email+'\n\n'+message, from_email, [ADMIN_EMAIL])
            except Exception:
                messages.info(
                    request,
                    u"""Error""")
            else:
                messages.info(request, u"Message sent")

            # redirect to same contact page with messages
            return HttpResponseRedirect(reverse('contact_admin'))

    # if there was not POST render blank form
    else:
        context = { 'form': ContactAdminForm()}

    return render(request, 'contact_admin/form.html', context)
'''

students/views/custom_contact_form.py
# writed as at https://atsoftware.de/2015/02/django-contact-form-full-tutorial-custom-example-in-django-1-7/
from collections import OrderedDict
from django import forms
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import FormView
from django.utils.translation import ugettext as _

from contact_form.forms import ContactForm

from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper

class CustomContactForm(ContactForm): # pragma: no cover
    def __init__(self, request, *args, **kwargs):
        super(CustomContactForm, self).__init__(request=request, *args, **kwargs)
        fields_keyOrder = ['name', 'email', 'body']
        self.fields = OrderedDict((field_name, self.fields[field_name]) for field_name in fields_keyOrder)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        #self.helper.form_action = reverse('contact-form')

        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'
        # button
        self.helper.add_input(Submit('send_button', _(u'Send')))

    recepient_list = [settings.ADMIN_EMAIL]
    name = forms.CharField(max_length=100,
                           label=_(u'Name'))
    email = forms.EmailField(max_length=200,
                             label=(_(u'Email')))
    body = forms.CharField(widget=forms.Textarea,
                           label=(_(u'Message')))


class CustomContactFormView(FormView): # pragma: no cover
    form_class = CustomContactForm
    template_name = 'contact_form/contact_form.html'

    def form_valid(self, form):
        form.save()
        return super(CustomContactFormView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CustomContactFormView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def get_success_url(self):
        return reverse('contact_form_sent')

students/views/set_language.py
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.urlresolvers import reverse


def set_language(request):
    if request.method == "POST":
        # get path refferer
        return_path = request.POST.get('return-path', reverse('home'))
        response = HttpResponseRedirect(return_path)
        # get lang_code of selected language
        selected_language = request.POST.get('lang', settings.LANGUAGE_CODE)
        # set cookie
        max_age = 10*365*24*60*60 # ten years
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME,
            selected_language,
            max_age=max_age)
        return response

students/templates/students/action_journal.html
{% extends "students/base.html" %}

{% load tz %}
{% load i18n %}
{% load el_pagination_tags %}

{% block meta_title %}{% trans "Action Journal (last 100 actions)" %}{% endblock meta_title %}

{% block title %}{% trans "Action Journal (last 100 actions)" %}{% endblock title %}

{% block content %}

{% paginate actions %}

<dl class="dl-horizontal">

    {% timezone "Europe/Kiev" %}

    {% for action in actions %}
    <div class="action-entry action-entry-{{action.model_name|lower}}">
        <dt class="action-entry-name">{% trans action.model_verbose_name|capfirst %} ({{action.timestamp|date:"d/m/Y H:i"}})</dt>
        <dd class="action-entry-detail">{{ action.action_detail|capfirst }}</dd>
    </div>
    {% endfor %}

    {% endtimezone %}

</dl>

{% show_pages %}

{% endblock %}

students/templates/students/base.html
{% load static from staticfiles %}
{% load i18n %}
{% load select_menu %}

<!DOCTYPE html>

<html lang="uk">
    <head>
        <meta charset="UTF-8"/>
        <title>{% trans "Students Accounting Service"%} - {% block meta_title %}{% endblock meta_title %}</title>
        <meta name="description"
            value="{% trans 'App to manage students database'%}" />
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

        <!-- Include Styles -->
        <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
        <link rel="stylesheet"
            href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet" href="{% static "css/main.css" %}">

            {# <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" /><!-- test popUp --> #}
        {# use file-upload plugin http://hayageek.com/docs/jquery-upload-file.php #}
        {# <link href="http://hayageek.github.io/jQuery-Upload-File/4.0.10/uploadfile.css" rel="stylesheet"> #}


    {% block extra_css %}{% endblock extra_css %}

    </head>
    <body>
        <div id="wrap">

        <!-- Start Containet -->
        <div class="container">

            <!-- Start Header -->
            <div class="row" id="header">

                <!-- Logo -->
                {% block logo %}
                <div class="col-xs-5">
                    <h2>{% trans "Students Accounting Service"%}</h2>
                </div>
                {% endblock logo %}

                <!-- Language Select -->
                <div class="col-xs-1" id='lang-select'>
                    <div class='lang-select-form'>
                        <form action="{% url "set_language" %}" method='post'>{% csrf_token %}
                            <input type='hidden' name='lang' value='uk'>
                            <input type='hidden' name='return-path' value='{{request.path}}'>
                            <button type='submit' class='btn btn-link'>Укр</button>
                        </form>
                    </div>
                    |
                    <div class='lang-select-form'>
                        <form action="{% url "set_language" %}" method='post'>{% csrf_token %}
                            <input type='hidden' name='lang' value='en'>
                            <input type='hidden' name='return-path' value='{{request.path}}'>
                            <button type='submit' class='btn btn-link'>Eng</button>
                        </form>
                    </div>
                </div>
                <!-- End Language Select -->

                <!-- Groups selector -->
                <div class="col-xs-3" id="group-selector">
                    <strong>{% trans "Group:" %}</strong>
                    <select>
                        <option value="">{% trans "All Students" %}</option>
                        {% for group in GROUPS %}
                        <option value="{{group.id }}" {% if group.selected %}selected="1"{% endif %}>
                            {{ group.title }}{% if group.leader %}, {{ group.leader }} {% endif %}
                        </option>
                        {% endfor %}
                    </select>
                </div>

                {% if user.is_authenticated %}
                <!-- User's toolbar for authenticated users -->
                <div class="col-xs-3" id="user-toolbar">
                    <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
                    <a href="{% url "auth_logout" %}">{% trans "Logout" %}</a>
                </div>

                {% else %}

                <!-- User's toolbar for anonymous users -->
                <div class="col-xs-3" id="user-toolbar">
                    <span>{% trans "Sign in with: " %}</span>
                    <a href="{% url "social:begin" "facebook" %}?next={{ request.path }}"><img class='img-rounded' heigh="25" width="25" src="{% static "img/fb_short.png" %}" alt="FB"></a>
                    <a href="{% url "social:begin" "twitter" %}?next={{ request.path }}"><img class='img-rounded' heigh="25" width="25" src="{% static "img/tw_short.png" %}" alt="Tw"></a>
                    <a href="{% url "social:begin" "google-oauth2" %}?next={{ request.path }}"><img class='img-rounded' heigh="25" width="25" src="{% static "img/g_short.png" %}" alt="G"></a>
                    <a href="{% url "social:begin" "vk-oauth2" %}?next={{ request.path }}"><img class='img-rounded' heigh="25" width="25" src="{% static "img/vk_short.png" %}" alt="Vk"></a><br>
                    <a href="{% url "users_login" %}">{% trans "Log in" %}</a> |
                    <a href="{% url "users:registration_register" %}">{% trans "Register" %}</a><br>
                </div>
                {% endif %}

            </div>
            <!-- End Header -->

            <!-- Start SubHeader -->
            <div class="row" id="sub-header">
                <div class="col-xs-12">
                    {% url 'home' as home_page %}
                    {% url 'journal' as journal_page %}
                    {% url 'groups' as groups_page %}
                    {% url 'action_journal' as actions_page %}
                    {% url 'users_list' as users_page %}
                    {% url 'contact_admin' as contact_admin %}
                    <ul class="nav nav-tabs">
                        <li role="presentation"
                            {% select_menu 'home' %}><a href="{{ home_page }}">{% trans "Students" %}</a></li>
                        <li role="presentation"
                            {% select_menu 'groups' %}><a href="{{ groups_page }}">{% trans "Groups" %}</a></li>
                        {% if user.is_authenticated %}
                        <li role="presentation"
                            {% select_menu 'journal' %}><a href="{{ journal_page }}">{% trans "Journal" %}</a></li>
                        <li role="presentation"
                            {% select_menu 'action_journal' %}><a href="{{ actions_page }}">{% trans "Action Journal" %}</a></li>
                        <li role="presentation"
                            {% select_menu 'users_list' %}><a href="{{ users_page }}">{% trans "Users" %}</a></li>
                        <li role="presentation"
                            {% select_menu 'contact_admin' %}><a href="{{ contact_admin }}">{% trans "Contact" %}</a></li>
                        {% else %}
                        <li role="presentation" class="disabled"
                            {% select_menu 'journal' %}><a href="{{ journal_page }}">{% trans "Journal" %}</a></li>
                        <li role="presentation" class="disabled"
                            {% select_menu 'action_journal' %}><a href="{{ actions_page }}">{% trans "Action Journal" %}</a></li>
                        <li role="presentation" class="disabled"
                            {% select_menu 'users_list' %}><a href="{{ users_page }}">{% trans "Users" %}</a></li>
                        <li role="presentation" class="disabled"
                            {% select_menu 'contact_admin' %}><a href="{{ contact_admin }}">{% trans "Contact" %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- End SubHeader -->

            <!-- Start Content Columns-->
            <div class="row" id="content-columns">
                <div class="col-xs-12" id="content-column">

                    {% block status_message %}
                      {% if messages %}
                        <div class="alert alert-warning" role="alert">
                            <ul>
                              {% for message in messages %}
                                <li >{{ message }}</li>
                              {% endfor %}
                            </ul>
                        </div>
                      {% endif %}
                        <div class="alert alert-danger" id="ajax-error">
                            <span id="ajax-error-text"></span>
                        </div>
                    {% endblock %}

                    <h2>{% block title %}{% endblock title %}</h2>
                    {% block content %}{% endblock content %}
                </div>
            </div>
            <!-- End Content Columns -->

            <!-- End Container -->
        </div>
        </div> {# id=wrap #}

        <!-- Start Footer -->
        <div class='container' id="footer">
                &copy; {% trans "Students Accounting Service" %}
        </div>
        <!-- End Footer -->

        <!-- Modal Boilerplate -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
                    </div>
                    <div id="modal-message-block" class="alert alert-danger" role="alert">
                        <span id="modal-message"></span>
                    </div>
                    <div class="modal-body"><!-- --></div>
                    <div class="modal-footer">
                        <div class='ajax-loader-modal'>
                            <img src='{% static "img/ajax-loader-bert2-white.gif" %}'>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ajax-loader"><img src='{% static "img/ajax-loader-bert2.gif" %}'></div>

        <!-- test code -->
        <!-- end test -->

        <!-- Javascript Section -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
        <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
        <script src="{% url "django.views.i18n.javascript_catalog" %}"></script>
        <script src="{% static "js/main.js" %}"></script>
        {# use file-upload plugin http://hayageek.com/docs/jquery-upload-file.php #}
        {# <script src="http://hayageek.github.io/jQuery-Upload-File/4.0.10/jquery.uploadfile.min.js"></script> #}
        {% block extra_js %}{% endblock extra_js %}

    </body>


</html>

students/templates/students/group_add.html
{% extends "students/base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{{ page_title }}{% endblock meta_title %}
{% block title %}{{ page_title }}{% endblock title %}
{% block status_message %}

{% if messages %}
    <div class="alert alert-warning" role="alert">
    Будь-ласка, виправте наступні помилки
        <ul>
          {% for message in messages %}
            <li >{{ message }}</li>
          {% endfor %}
        </ul>

    </div>
{% endif %}
{% endblock %}


{% block content %}

    {% crispy form %}

{% endblock content %}

students/templates/students/groups_add.html
{% extends "students/base.html" %}

{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block meta_title %}{{ page_title }}{% endblock meta_title %}
{% block title %}{{ page_title }}{% endblock title %}

{% block status_message %}

{% if messages %}
    <div class="alert alert-warning" role="alert">
        {% trans "Please, check the errors" %}
        <ul>
          {% for message in messages %}
            <li >{{ message }}</li>
          {% endfor %}
        </ul>

    </div>
{% endif %}
{% endblock %}


{% block content %}

    {% crispy form %}

{% endblock content %}

students/templates/students/groups_confirm_delete.html
{% extends "students/base.html" %}

{% load static from staticfiles %}
{% load i18n %}

{% block meta_title %}{% trans "Delete Group"%}{% endblock meta_title %}
{% block title %}{% trans "Delete Group"%}{% endblock title %}

{% block content %}
<form action="{% url "group_delete" object.id %}" method="post">
    {% csrf_token %}
    <p>
        {% blocktrans %}Do you really want to delete group "{{ object }}"?{% endblocktrans %}
    </p>
    <input type="submit" value="{% trans "Yes"%}" name="delete_button"
        class="btn btn-danger">
    <a href="{% url "groups" %}" class="btn btn-info">{% trans "No" %}</a>
</form>
{% endblock content %}